name: ðŸš€ Deploy only JS to Production

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn packages
        run: yarn install

      - name: Build frontend assets
        run: yarn run build

      - name: ðŸšš FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.SERVER }}
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/bin/**
            **/assets/**
            **/node_modules/**
            **/public/bundles/**
            **/src/**
            **/templates/**
            **/tests/**
            **/translations/**
            **/var/**
            **/vendor/**
            .env
            .env.*
